spring.application.name=backend_usuario

# 1. PARÁMETROS DE CONEXIÓN
spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ksstyenameqvwcewlgvz
spring.datasource.password=lumiskin123#
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. CONFIGURACIÓN DE JPA (CORREGIDO DE MYSQL A POSTGRESQL)
spring.jpa.hibernate.ddl-auto=update   
# Se cambió MySQL8Dialect por PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# 3. ESQUEMA Y LOGS
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Asegúrate de haber creado el esquema 'usuario' en Supabase
spring.jpa.properties.hibernate.default_schema=usuario

# 4. PUERTO
server.port=8082

# 5. CONFIGURACIÓN JWT
jwt.secret=FN28fhs82HF82hf8H2F8HF82hf82HF82hf82Hf82HF82hf8
jwt.expiration=3600000

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

#6 Configuracion para recuperacion de contraseña
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000