spring.application.name=backend_inventario

# 1. PARÁMETROS DE CONEXIÓN
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.igxfoirznluieitymvyj
spring.datasource.password=lumiskin123#
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. CONFIGURACIÓN DE JPA (CORREGIDO: POSTGRESQL)
spring.jpa.hibernate.ddl-auto=update   
# Cambiamos MySQL8Dialect por PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# 3. LOGS Y ESQUEMA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Asegúrate de ejecutar: CREATE SCHEMA IF NOT EXISTS inventario; en Supabase
spring.jpa.properties.hibernate.default_schema=inventario

# 4. SERVIDOR
server.port=8081

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

# 5. CREDENCIALES DE SUPABASE STORAGE
supabase.url=https://igxfoirznluieitymvyj.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlneGZvaXJ6bmx1aWVpdHltdnlqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODUzNTA2OCwiZXhwIjoyMDk0MTExMDY4fQ.a9WUKenefOJ1PoHDUqc6vuciF_c1xSxdC_rMHx2bS2o