spring.application.name=backend_pago

# 1. PARÁMETROS DE CONEXIÓN (CORREGIDOS)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.hbuvjtqitsjualwaxsxh
spring.datasource.password=lumiskin123#
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. CONFIGURACIÓN DE JPA (CAMBIADO DE MYSQL A POSTGRES)
spring.jpa.hibernate.ddl-auto=update   

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# 3. ESQUEMA Y LOGS
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Asegúrate de que el esquema "pago" exista en tu base de datos de Supabase
spring.jpa.properties.hibernate.default_schema=pago

# 4. CONFIGURACIÓN WEBPAY / JWT
jwt.secret=MiClaveUltraSecretaParaPago123456
jwt.expiration=3600000

# 5. SERVIDOR
server.port=8083